language: ruby
rvm:
  - 2.3.1
script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "EHoP8CoHLKKTEXLoq54SYFLaOvKUNfLBXCEIkHGwj9zK6zcMQfhHF5d00yYgiR4BHFXpREhCD3oMe6BoZNd/7LGvYubXOysH4wAQBhX1aRy2lJ0XdKzeANSGH8HcD2QsZLSBlZ1PjPiJQ0m3HXDC8oC1uxCO/LAlhIhzsHzWtWcGUlCwFkEeYgu1gwLM00E/fuHITjhorDufS5VZ/csTtbko14DdqmZyf/Ed/Hmmq8rYR724fpL5HRyZfmIJblsTC5cMBF/rj4S5IatK4Zauw/WI4+s9tUCtmrBmDZtd4I7Jv2ucxMbPJNEqdy25AgZYRCneDyEsO+7ab5+AZY9nZEEsnkBH0omGIsZHxoAK1Zx72xBNvNxwkEtxUDqEDSxvMbxz8xqTeRFhBPgwk98xUZCAzYXzNfAQZ5M2Xvj8k5+j9mx/MDd3kZVgNcgdfoPHZSMgXAE7EZoMQBYCB6wTDgkVM3KsFS4XH1pfIh0NlAoQwdNoDl2emCLBhYy3AkXAJP+aowKIOr2NZ8v0zvg/DGa7q2RraEKOyL5IlvfCoKUXNnaTm8xNnLsa23USRIJ+S8DwzavTFPkmhBGLLaIJ0p1DD0jjIbft6NWvRd5ck/HgUIqIMZPjMWPCa4OSGHzDIrOfKnS6BDd3Wws6luAejR0y8aXk3TykEPiDWgaWK40="
